### ISSUE TITLE
TraitEntityID should support other types beside string

### ISSUE THREAD

**Issue by muhametk** [max-bytes/omnikeeper#119]
For code-first trait generation when marking a field as **TraitEntityID** for types that arn't string an error is thrown, since only strings are supported currently.

Since there are CIs that are distinguished by theyre int ID it would be helpful for selecting the correct trait items.

**Comment by maximiliancsuk** [comment]
The type `long` is supported as a TraitEntityID out of the box. If you use that instead of `int` it should work.
