### ISSUE TITLE
Supporting multiple columns as TraitEntityID

### ISSUE THREAD

**Issue by muhametk** [max-bytes/omnikeeper#120]
In original data there are cases that primary key is built with multiple columns. 

Currently for code-first trait generation through TraitEntityID we can specify only one column as primary key which causes that the incorrect number of rows to be fetched through the specified trait.

**Comment by maximiliancsuk** [comment]
Is now supported with #122 

Have a look at https://github.com/max-bytes/omnikeeper/blob/master/backend/Tests/Integration/Model/GenericTraitEntityModelTest.cs#L184 for an example how to use an entity with an ID that consists of multiple fields.
