### ISSUE TITLE
Generators: support for optional referenced attributes

### ISSUE THREAD

**Issue by maximiliancsuk** [max-bytes/omnikeeper#89]
Currently, a generated attribute is only created when ALL of the referenced attributes exist. Allow generatos more fine-grained control over when a generated attribute should be created, like when an attribute does NOT exist, allow the template to decide whether or not to still produce a generated attribute.

**Comment by mho21** [comment]
+1

**Comment by mho21** [comment]
+1

**Comment by maximiliancsuk** [comment]
Fixed in 3d58481e225c23ffb2d7f2282cc1db4c5535dcf2

Will be released in 5.0.0
